rootDirectory  App files
services:
  - type: web
    name: fgb-render
    env: python
    plan: free
    rootDirectory: App files      # ðŸ‘ˆ tells Render where main.py lives
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
